<?php

namespace Bolero\Forms\Plugins\Router;

use Bolero\Forms\Components\Component;
use Bolero\Forms\Core\Builder;
use Bolero\Forms\Registry\ComponentRegistry;
use Bolero\Forms\Registry\HttpErrorRegistry;
use Bolero\Forms\Registry\RouteRegistry;

use function Bolero\Forms\Hooks\useEffect;
use function Bolero\Forms\Hooks\useState;

function Router($children)
{
    useEffect(function (/* bool */ $hasRouted, /* object */ $service, /* string */ $path, /* string */ $html) {

        $service = new RouterService;

        if (RouteRegistry::hasMoved()) {

            [$path, $query, $error, $code] = $service->doRouting();
            $service->renderRoute($code === 200, $path, $query, $error, $code, $html);

            $hasRouted = true;
        }
    });

    return (<<< HTML
        <%
            if(%hasRouted) { 
                { html }
                return;
            }
        %>
        {{ children }}
        <%            
            rename(RouteRegistry::getCacheFilename(), RouteRegistry::getMovedFilename());
            Builder::purgeCopies();

            %service->findRoute(%html);
            if(%html !== '') { 
                { html }
            } 

        %>
    HTML);
}
