<?php

namespace Bolero\Forms\Plugins\HtmlSaver;

use function Bolero\Forms\Hooks\useEffect;

function HtmlSaver($children): string
{
    useEffect(function($children, $service) {
        $service = new HtmlSaverService($children);
    });

    return (<<< HTML
        @if %service->canRender() do
        {{ children }}
        @done
        <% 
            if(!%service->isPending()) {
                %service->markAsPending();
                %html = { children };
                %service->storeHTML(%html);
            }
        %>
    HTML);
}
